//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gyro3dMonitor.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Gyro3dMonitor.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Close に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_Close {
            get {
                return ResourceManager.GetString("button_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Displaying a view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_DisplayModel {
            get {
                return ResourceManager.GetString("button_DisplayModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Update the view に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_DisplayModelUpdate {
            get {
                return ResourceManager.GetString("button_DisplayModelUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Loading STL model に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_LoadModel {
            get {
                return ResourceManager.GetString("button_LoadModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gyro monitor cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_MonitorOff {
            get {
                return ResourceManager.GetString("button_MonitorOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Gyro monitor start に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_MonitorOnOff {
            get {
                return ResourceManager.GetString("button_MonitorOnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Capture &amp; save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_SaveImage {
            get {
                return ResourceManager.GetString("button_SaveImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ... に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string button_SelectBitmap {
            get {
                return ResourceManager.GetString("button_SelectBitmap", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Check floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkBox_CheckGround {
            get {
                return ResourceManager.GetString("checkBox_CheckGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Coordinate axes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkBox_CoordinateAxes {
            get {
                return ResourceManager.GetString("checkBox_CoordinateAxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Mesh floor に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkBox_MeshGround {
            get {
                return ResourceManager.GetString("checkBox_MeshGround", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Shadow (floor height fixed at zero) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkBox_shadowEnable {
            get {
                return ResourceManager.GetString("checkBox_shadowEnable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Skydome ---&gt; に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string checkBox_SkyDome {
            get {
                return ResourceManager.GetString("checkBox_SkyDome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Quaternion;Euler Angles に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string comboBox_RotationMethod_Items {
            get {
                return ResourceManager.GetString("comboBox_RotationMethod_Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_BackgroundColor {
            get {
                return ResourceManager.GetString("label_BackgroundColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Color palette: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_ColorPalette {
            get {
                return ResourceManager.GetString("label_ColorPalette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   far: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_far {
            get {
                return ResourceManager.GetString("label_far", resourceCulture);
            }
        }
        
        /// <summary>
        ///   FOV: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_FOV {
            get {
                return ResourceManager.GetString("label_FOV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Gyro operation ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_GyroOperation {
            get {
                return ResourceManager.GetString("label_GyroOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ] Hight: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_Hight {
            get {
                return ResourceManager.GetString("label_Hight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lighting: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_LightingColor {
            get {
                return ResourceManager.GetString("label_LightingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_MaterialColor {
            get {
                return ResourceManager.GetString("label_MaterialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   near: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_near {
            get {
                return ResourceManager.GetString("label_near", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Port: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_Port {
            get {
                return ResourceManager.GetString("label_Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Radius: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_Radius {
            get {
                return ResourceManager.GetString("label_Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rotation method: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_RotationMethod {
            get {
                return ResourceManager.GetString("label_RotationMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (s): に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_Timeout {
            get {
                return ResourceManager.GetString("label_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Viewer operation ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_ViewerOperation {
            get {
                return ResourceManager.GetString("label_ViewerOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   [ Viewport settings (VP ​​is auto) ] に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_ViewportSettings {
            get {
                return ResourceManager.GetString("label_ViewportSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   VP x,y,z: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_VP {
            get {
                return ResourceManager.GetString("label_VP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   W, H: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string label_WH {
            get {
                return ResourceManager.GetString("label_WH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing a model file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_1 {
            get {
                return ResourceManager.GetString("msgMain_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   PNG image (*.png)|*.png|JPEG image (*.jpg)|*.jpg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_10 {
            get {
                return ResourceManager.GetString("msgMain_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An error has occurred: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_11 {
            get {
                return ResourceManager.GetString("msgMain_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The model is not loaded. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_12 {
            get {
                return ResourceManager.GetString("msgMain_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The view is not visible. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_13 {
            get {
                return ResourceManager.GetString("msgMain_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   STL Model (*.stl)|*.stl に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_2 {
            get {
                return ResourceManager.GetString("msgMain_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_3 {
            get {
                return ResourceManager.GetString("msgMain_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Importing image files に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_4 {
            get {
                return ResourceManager.GetString("msgMain_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Image file (*.jpg)|*.jpg に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_5 {
            get {
                return ResourceManager.GetString("msgMain_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   File not found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_6 {
            get {
                return ResourceManager.GetString("msgMain_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no capture image. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_7 {
            get {
                return ResourceManager.GetString("msgMain_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   There is no image data. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_8 {
            get {
                return ResourceManager.GetString("msgMain_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to save the captured image? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgMain_9 {
            get {
                return ResourceManager.GetString("msgMain_9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The gyro monitor has been interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgView_1 {
            get {
                return ResourceManager.GetString("msgView_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The gyro sensor could not be received (timed out). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgView_2 {
            get {
                return ResourceManager.GetString("msgView_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication was interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgView_3 {
            get {
                return ResourceManager.GetString("msgView_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Communication was interrupted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgView_4 {
            get {
                return ResourceManager.GetString("msgView_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Socket error: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string msgView_5 {
            get {
                return ResourceManager.GetString("msgView_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_Dark {
            get {
                return ResourceManager.GetString("radioButton_Dark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_Light {
            get {
                return ResourceManager.GetString("radioButton_Light", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Lighting color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_LightingColor {
            get {
                return ResourceManager.GetString("radioButton_LightingColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Material color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_MaterialColor {
            get {
                return ResourceManager.GetString("radioButton_MaterialColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Background color: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_RGBColor {
            get {
                return ResourceManager.GetString("radioButton_RGBColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Texture: に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string radioButton_Texture {
            get {
                return ResourceManager.GetString("radioButton_Texture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CANCEL に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Cancel {
            get {
                return ResourceManager.GetString("StateMonitor_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OFFLINE に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Offline {
            get {
                return ResourceManager.GetString("StateMonitor_Offline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   RECEIVING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Receiving {
            get {
                return ResourceManager.GetString("StateMonitor_Receiving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   sec に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Receiving_Unit {
            get {
                return ResourceManager.GetString("StateMonitor_Receiving_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   TIMEOUT に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Timeout {
            get {
                return ResourceManager.GetString("StateMonitor_Timeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   WAITING に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string StateMonitor_Waiting {
            get {
                return ResourceManager.GetString("StateMonitor_Waiting", resourceCulture);
            }
        }
    }
}
